#!/usr/bin/bash

trap 'Update' 5

background="#2d2d2d"

Format() {
    echo "%{+u}%{B$background} $1 %{B}%{-u}"
}

Workspaces() {
    desktops=$(bspc query -D --names)
    focused=$(bspc query -D --names -d focused)

    for desktop in $desktops; do
        desktop=$(echo "$desktop")
        nodes=$(bspc query -N -d $desktop)

        if [ ! -z "$nodes" ]; then
            desktops=$(echo $desktops | sed "s/$desktop/%{F#ff0000}$desktop%{F-}/")
        fi

    done
    desktops=$(echo $desktops | sed "s/$focused/%{B$background}%{+u}_$focused\_%{-u}%{B-}/")

    echo $desktops | sed "s/_/ /g"
}

ActiveWindow() {
    printf " $(xdotool getwindowfocus getwindowname)"
}

Clock() {
    DATE=$("%d/%m/%y")
    TIME=$("%I:%M:%S")

    Format "$(DATE) $(TIME)"
}

Update() {
    echo -e "%{l}$(Workspaces) $(ActiveWindow) %{r} $(Clock)"
}

while true; do
    Update
    wait
done
