#!/usr/bin/bash

# ~/.lemonbar/lemonconfig

trap 'Update' 5

background="#282a36"

Clock(){
	TIME=$(date "+%H:%M")
	echo -e -n " \uf017 %{F#ff5555}-- ${TIME} -- %{F#bbc2cf}"
}

Cal() {
    DATE=$(date "+%A, %d %m %Y ")
    echo -e -n "\uf073 %{F#faef57}${DATE}"
}

ActiveWindow(){
	len=$(echo -n "  -  $(xdotool getwindowfocus getwindowname)" | wc -m)
	max_len=70
	if [ "$len" -gt "$max_len" ];then
		echo -n "  -  $(xdotool getwindowfocus getwindowname | cut -c 1-$max_len)..."
	else
		echo -n "  -  $(xdotool getwindowfocus getwindowname)"
	fi
}

Workspaces() {
    desktops=$(bspc query -D --names)
    focused=$(bspc query -D --names -d focused)

    for desktop in $desktops; do
        desktop=$(echo "$desktop")
        nodes=$(bspc query -N -d $desktop)

        if [ ! -z "$nodes" ]; then
            desktops=$(echo $desktops | sed "s/$desktop/%{F#0388fc}$desktop%{F#bbc2cf}/")
        fi

    done
    desktops=$(echo $desktops | sed "s/$focused/%{B$background}%{F#0388fc}%{+u}_$focused\_%{-u}%{B-}/")

    echo $desktops | sed "s/_/ /g"
}

while true; do
	echo -e "%{l}$(Workspaces) $(ActiveWindow)" "%{r}$(Cal) $(Clock)"
	sleep 0.1s
done
