#!/usr/bin/env bash

#  _____ ____
# |  _  |    \
# |     |  |  |
# |__|__|____/
#
# Alededorigo Herbstluftwm Configuration
# Place this file into ~/.config/herbstluftwm/autostart
# https://github.com/alededorigo/dotfiles
# https://gitlab.com/alededorigo/dotfiles
#

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all

# --- VARIABLES --- #
bg="#282a36"
ac="#bd93f9"
Mod=Mod4

# --- KEYBINDS --- #
hc keybind $Mod-Shift-c quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
# Layout
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space
# Focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
# Move
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right
# Split
hc keybind $Mod-u       split   bottom  0.6
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-j	split	left	0.3
# Resize
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# --- TAGS --- #
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

                                                          \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# --- MOUSE --- #
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# --- THEME --- #
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $ac
hc set frame_border_normal_color $bg
#hc set frame_bg_normal_color '#2E3440'
#hc set frame_bg_active_color '#2E3440'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 2
hc set frame_padding 0
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc attr theme.active.color $bg
hc attr theme.normal.color $bg
hc attr theme.urgent.color $bg
hc attr theme.inner_width 1
hc attr theme.inner_color $bg
hc attr theme.border_width 27
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $bg
hc attr theme.active.outer_color $bg
hc attr theme.background_color $bg

# --- POLYBAR --- #
~/.config/polybar/launch.sh

# --- ROFI --- #
hc keybind $Mod-space spawn rofi -show drun -lines 10 -padding 480 -theme AD

# --- WALLPAPER SET --- #
nitroegen --restore &

# --- RULES --- #
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc set tree_style '╾│ ├└╼─┐'

# --- UNLOCK --- #
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

