#!/bin/bash

# ~/.config/VARS
# Some variables that i use. Add this in .bashrc:
# source "$HOME/.config/VARS"

CONF_DIR="$HOME/.config/"
III_DIR="$HOME/.config/i3/"
NOTI_DIR="$HOME/.config/dunst/"
SCRIPTS_DIR="$HOME/.scripts/"
BG_DIR="$HOME/Pictures/walls"
MUS_DIR="$HOME/Music/"

BG_COL="#111217"
FG_COL="#ffffff"
AC_COL="#7ab8c9"

GIT_SCRIPT="$SCRIPTS/github.sh"
