#!/bin/bash

# ~/.config/VARS
# Some variables that i use. Add this in .bashrc:
# source "$HOME/.config/VARS"

CONF_DIR="$HOME/.config/"
III_DIR="$HOME/.config/i3/"
NOTI_DIR="$HOME/.config/dunst/"
SCRIPTS_DIR="$HOME/.scripts/"
BG_DIR="$HOME/Pictures/walls"
MUS_DIR="$HOME/Music/"

BG_COL="#111217"
FG_COL="#ffffff"
AC_COL="#ba8991"

SCRIPTS="$HOME/.scripts"
GIT_SCRIPT="$SCRIPTS/git"

TODO_FILE=~/.config/rofi/scripts/todos
NOTE=$(cat $TODO_FILE | tail -n 1)
