#! /bin/sh

#  _____ ____
# |  _  |    \
# |     |  |  |
# |__|__|____/
#
# Alededorigo Polybar Configuration
# Place this file into ~/.config/polybar/config
# https://github.com/alededorigo/dotfiles
# https://gitlab.com/alededorigo/dotfiles
#

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
picom --config=.config/picom/picom.conf

bspc monitor -d ter web dev ter oth img fil lst

bspc config border_width         2
bspc config active_border_color  "#ca9dee"
bspc config normal_border_color  "#44475a"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a  state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
