#! /bin/sh

#  _____ ____
# |  _  |    \
# |     |  |  |
# |__|__|____/
#
# Alededorigo Bspwm Configuration
# Place this file into ~/.config/bspwm/bspwmrc
# https://github.com/alededorigo/dotfiles
# https://gitlab.com/alededorigo/dotfiles
#

# --- WORKSPACES --- #
bspc monitor -d 1 2 3 4 5 6 7

# --- AUTOSTART PROGRAMS --- #
sxhkd &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh

# --- LAYOUT --- #
bspc config border_width                  1
bspc config window_gap                    4
bspc config split_ratio                   0.60
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# --- COLORS --- #
bspc config normal_border_color		      "#d65d0e"
bspc config active_border_color	              "#282828"
bspc config focused_border_color	      "#d65d0e"

# --- RULES --- #
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'

