#! /bin/sh

# ~/.config

# --- WORKSPACES --- #
bspc monitor -d 1 2 3 4 5 6 7

# --- AUTOSTART --- #
sxhkd &
nitrogen --restore &
if ! pgrep cbatticon; then
    /usr/bin/cbatticon -i standard -l 20
fi
unclutter &
bash .config/polybar/launch.sh &
setxkbmap -layout us &
xsettingsd &

# --- LAYOUT --- #
bspc config border_width                  2
bspc config window_gap                    12
bspc config split_ratio                   0.60
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# --- COLORS --- #
bspc config normal_border_color		      "#20242a"
bspc config active_border_color	              "#20242a"
bspc config focused_border_color	      "#ba8991"

# --- RULES --- #
bspc rule -a Gimp desktop='^6' state=floating follow=on
