#!bin/sh
# Replace any panel to maximize space

# Notify stats

killall dunst

dunst &

bash ~/.scripts/notify-send.sh " Stats ⚡" " Now $(date +"%H:%M") \n Day $(date +"%d %b") \n Bat $(cat /sys/class/power_supply/BAT0/capacity)% \n Cpu $(sensors | grep '[Cc]ore 0: ' | sed "s/Core 0:        //" | sed "s/(high = +100.0°C, crit = +100.0°C)//") \n Ram $(free -m | awk 'NR==2{printf "%sM", $3,$2,$3*100/$2 }')"
